name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Test backend syntax
      run: |
        cd backend
        pip install -r requirements.txt
        python -m py_compile app.py
    
    - name: Test frontend syntax
      run: |
        cd frontend
        pip install -r requirements.txt
        python -m py_compile app.py
    
    - name: Test logger syntax
      run: |
        cd logger
        pip install -r requirements.txt
        python -m py_compile app.py

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Backend image
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/devops-backend:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/devops-backend:${{ github.sha }}
    
    - name: Build and push Frontend image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/devops-frontend:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/devops-frontend:${{ github.sha }}
    
    - name: Build and push Logger image
      uses: docker/build-push-action@v4
      with:
        context: ./logger
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/devops-logger:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/devops-logger:${{ github.sha }}